name: Create Documentation
on:
  push:
    branches:
      - main
      - docs/mkdocs
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install your package to ensure autodoc works
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
        
      - name: Install package with docs dependencies
        run: python -m pip install -r requirements.txt

      # Build the MkDocs documentation
      - name: Build Documentation
        run: |
          mkdocs build --clean

      # Deploy the built documentation to the gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site  # MkDocs builds to the 'site' directory by default